// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkIB9i3HiDvIRnZOiUhtMsKQRlLmHUbXs',
    appId: '1:204742374983:web:40390f97bd633c48aae362',
    messagingSenderId: '204742374983',
    projectId: 'rental-app-68251',
    authDomain: 'rental-app-68251.firebaseapp.com',
    storageBucket: 'rental-app-68251.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNVg3Pt00uUaqzj9huGL7WIVGmLfzTV-0',
    appId: '1:204742374983:android:93f104a7aaa2fed6aae362',
    messagingSenderId: '204742374983',
    projectId: 'rental-app-68251',
    storageBucket: 'rental-app-68251.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABqpZnflp7re4hxnft2sxdz0fCdclvado',
    appId: '1:204742374983:ios:7cc1f2a738543675aae362',
    messagingSenderId: '204742374983',
    projectId: 'rental-app-68251',
    storageBucket: 'rental-app-68251.appspot.com',
    iosClientId: '204742374983-6sbpm0ibhoaecoc1hv4aaut9hkvj3er1.apps.googleusercontent.com',
    iosBundleId: 'com.example.rentalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABqpZnflp7re4hxnft2sxdz0fCdclvado',
    appId: '1:204742374983:ios:c474dcd3d90af253aae362',
    messagingSenderId: '204742374983',
    projectId: 'rental-app-68251',
    storageBucket: 'rental-app-68251.appspot.com',
    iosClientId: '204742374983-dl8blcu4738pgn3ndvhkbruhb1djh8h3.apps.googleusercontent.com',
    iosBundleId: 'com.example.rentalApp.RunnerTests',
  );
}
